#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OutInDB
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="outinDB")]
	public partial class OutInDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertTbCargo(TbCargo instance);
    partial void UpdateTbCargo(TbCargo instance);
    partial void DeleteTbCargo(TbCargo instance);
    partial void InsertTbTipoMovimiento(TbTipoMovimiento instance);
    partial void UpdateTbTipoMovimiento(TbTipoMovimiento instance);
    partial void DeleteTbTipoMovimiento(TbTipoMovimiento instance);
    partial void InsertTbCategoria(TbCategoria instance);
    partial void UpdateTbCategoria(TbCategoria instance);
    partial void DeleteTbCategoria(TbCategoria instance);
    partial void InsertTbEmpleados(TbEmpleados instance);
    partial void UpdateTbEmpleados(TbEmpleados instance);
    partial void DeleteTbEmpleados(TbEmpleados instance);
    partial void InsertTbMovimiento(TbMovimiento instance);
    partial void UpdateTbMovimiento(TbMovimiento instance);
    partial void DeleteTbMovimiento(TbMovimiento instance);
    partial void InsertTbProducto(TbProducto instance);
    partial void UpdateTbProducto(TbProducto instance);
    partial void DeleteTbProducto(TbProducto instance);
    partial void InsertTbTipoId(TbTipoId instance);
    partial void UpdateTbTipoId(TbTipoId instance);
    partial void DeleteTbTipoId(TbTipoId instance);
    #endregion
		
		public OutInDBDataContext() : 
				base(global::OutInDB.Properties.Settings.Default.outinDBConnectionString4, mappingSource)
		{
			OnCreated();
		}
		
		public OutInDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OutInDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OutInDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OutInDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TbCargo> TbCargo
		{
			get
			{
				return this.GetTable<TbCargo>();
			}
		}
		
		public System.Data.Linq.Table<TbTipoMovimiento> TbTipoMovimiento
		{
			get
			{
				return this.GetTable<TbTipoMovimiento>();
			}
		}
		
		public System.Data.Linq.Table<TbCategoria> TbCategoria
		{
			get
			{
				return this.GetTable<TbCategoria>();
			}
		}
		
		public System.Data.Linq.Table<TbEmpleados> TbEmpleados
		{
			get
			{
				return this.GetTable<TbEmpleados>();
			}
		}
		
		public System.Data.Linq.Table<TbMovimiento> TbMovimiento
		{
			get
			{
				return this.GetTable<TbMovimiento>();
			}
		}
		
		public System.Data.Linq.Table<TbOrdenCompra> TbOrdenCompra
		{
			get
			{
				return this.GetTable<TbOrdenCompra>();
			}
		}
		
		public System.Data.Linq.Table<TbProducto> TbProducto
		{
			get
			{
				return this.GetTable<TbProducto>();
			}
		}
		
		public System.Data.Linq.Table<TbProveedor> TbProveedor
		{
			get
			{
				return this.GetTable<TbProveedor>();
			}
		}
		
		public System.Data.Linq.Table<TbTipoId> TbTipoId
		{
			get
			{
				return this.GetTable<TbTipoId>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.accederEmpleado")]
		public ISingleResult<accederEmpleadoResult> accederEmpleado([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string usuario, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string contrasena)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), usuario, contrasena);
			return ((ISingleResult<accederEmpleadoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.verEmpleados")]
		public ISingleResult<verEmpleadosResult> verEmpleados()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<verEmpleadosResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.crearCatgoria")]
		public int crearCatgoria([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string des)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), des);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.crearProducto")]
		public int crearProducto([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> cantidad, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Precio", DbType="Money")] System.Nullable<decimal> precio, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Unidades", DbType="Int")] System.Nullable<int> unidades, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> sMin, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> sMax, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string cantXunidad, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Cat", DbType="Int")] System.Nullable<int> cat)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombre, cantidad, precio, unidades, sMin, sMax, cantXunidad, cat);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.eliminarCategoria")]
		public int eliminarCategoria([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.eliminarEmpleado")]
		public int eliminarEmpleado([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.eliminarProducto")]
		public int eliminarProducto([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.eliminarProveedor")]
		public int eliminarProveedor([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Insertar_Movimientos")]
		public int Insertar_Movimientos([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> fecha, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> prod, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> cantP, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Emple", DbType="VarChar(30)")] string emple, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Ubicac", DbType="VarChar(10)")] string ubicac, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> tipo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> conec)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), fecha, prod, cantP, emple, ubicac, tipo, conec);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.insertarOrdenCompra")]
		public int insertarOrdenCompra([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> moFecha, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> moProducto, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> moCnat, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string moEmp, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string moUbi, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> moTipo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Prec", DbType="Money")] System.Nullable<decimal> prec)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), moFecha, moProducto, moCnat, moEmp, moUbi, moTipo, prec);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.InsertarProveedor")]
		public int InsertarProveedor([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombre", DbType="VarChar(70)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Contacto", DbType="VarChar(50)")] string contacto, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Direccion", DbType="VarChar(50)")] string direccion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombre, contacto, direccion);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.listar_Movimientos")]
		public ISingleResult<listar_MovimientosResult> listar_Movimientos()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<listar_MovimientosResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.listarCatgoria")]
		public ISingleResult<listarCatgoriaResult> listarCatgoria()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<listarCatgoriaResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.listarOrdenCompra")]
		public ISingleResult<listarOrdenCompraResult> listarOrdenCompra()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<listarOrdenCompraResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.listarProductos")]
		public ISingleResult<listarProductosResult> listarProductos()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<listarProductosResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.listarProveedor")]
		public ISingleResult<listarProveedorResult> listarProveedor()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<listarProveedorResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.registrarEmpleado")]
		public int registrarEmpleado([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> nacimiento, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(70)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string contrasena, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> tipo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string dir, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> cargo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(60)")] string telefono)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id, nacimiento, nombre, contrasena, tipo, dir, cargo, telefono);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TbCargo")]
	public partial class TbCargo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ca_Id;
		
		private string _ca_Descripcion;
		
		private EntitySet<TbEmpleados> _TbEmpleados;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onca_IdChanging(int value);
    partial void Onca_IdChanged();
    partial void Onca_DescripcionChanging(string value);
    partial void Onca_DescripcionChanged();
    #endregion
		
		public TbCargo()
		{
			this._TbEmpleados = new EntitySet<TbEmpleados>(new Action<TbEmpleados>(this.attach_TbEmpleados), new Action<TbEmpleados>(this.detach_TbEmpleados));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ca_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ca_Id
		{
			get
			{
				return this._ca_Id;
			}
			set
			{
				if ((this._ca_Id != value))
				{
					this.Onca_IdChanging(value);
					this.SendPropertyChanging();
					this._ca_Id = value;
					this.SendPropertyChanged("ca_Id");
					this.Onca_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ca_Descripcion", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string ca_Descripcion
		{
			get
			{
				return this._ca_Descripcion;
			}
			set
			{
				if ((this._ca_Descripcion != value))
				{
					this.Onca_DescripcionChanging(value);
					this.SendPropertyChanging();
					this._ca_Descripcion = value;
					this.SendPropertyChanged("ca_Descripcion");
					this.Onca_DescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TbCargo_TbEmpleados", Storage="_TbEmpleados", ThisKey="ca_Id", OtherKey="em_cargo")]
		public EntitySet<TbEmpleados> TbEmpleados
		{
			get
			{
				return this._TbEmpleados;
			}
			set
			{
				this._TbEmpleados.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TbEmpleados(TbEmpleados entity)
		{
			this.SendPropertyChanging();
			entity.TbCargo = this;
		}
		
		private void detach_TbEmpleados(TbEmpleados entity)
		{
			this.SendPropertyChanging();
			entity.TbCargo = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TbTipoMovimiento")]
	public partial class TbTipoMovimiento : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Tmo_IdTipoMovimiento;
		
		private string _Tmo_Nombre;
		
		private EntitySet<TbMovimiento> _TbMovimiento;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTmo_IdTipoMovimientoChanging(int value);
    partial void OnTmo_IdTipoMovimientoChanged();
    partial void OnTmo_NombreChanging(string value);
    partial void OnTmo_NombreChanged();
    #endregion
		
		public TbTipoMovimiento()
		{
			this._TbMovimiento = new EntitySet<TbMovimiento>(new Action<TbMovimiento>(this.attach_TbMovimiento), new Action<TbMovimiento>(this.detach_TbMovimiento));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tmo_IdTipoMovimiento", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Tmo_IdTipoMovimiento
		{
			get
			{
				return this._Tmo_IdTipoMovimiento;
			}
			set
			{
				if ((this._Tmo_IdTipoMovimiento != value))
				{
					this.OnTmo_IdTipoMovimientoChanging(value);
					this.SendPropertyChanging();
					this._Tmo_IdTipoMovimiento = value;
					this.SendPropertyChanged("Tmo_IdTipoMovimiento");
					this.OnTmo_IdTipoMovimientoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tmo_Nombre", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string Tmo_Nombre
		{
			get
			{
				return this._Tmo_Nombre;
			}
			set
			{
				if ((this._Tmo_Nombre != value))
				{
					this.OnTmo_NombreChanging(value);
					this.SendPropertyChanging();
					this._Tmo_Nombre = value;
					this.SendPropertyChanged("Tmo_Nombre");
					this.OnTmo_NombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TbTipoMovimiento_TbMovimiento", Storage="_TbMovimiento", ThisKey="Tmo_IdTipoMovimiento", OtherKey="mo_IdTipo")]
		public EntitySet<TbMovimiento> TbMovimiento
		{
			get
			{
				return this._TbMovimiento;
			}
			set
			{
				this._TbMovimiento.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TbMovimiento(TbMovimiento entity)
		{
			this.SendPropertyChanging();
			entity.TbTipoMovimiento = this;
		}
		
		private void detach_TbMovimiento(TbMovimiento entity)
		{
			this.SendPropertyChanging();
			entity.TbTipoMovimiento = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TbCategoria")]
	public partial class TbCategoria : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _cat_Id;
		
		private string _cat_Descripcion;
		
		private EntitySet<TbProducto> _TbProducto;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncat_IdChanging(int value);
    partial void Oncat_IdChanged();
    partial void Oncat_DescripcionChanging(string value);
    partial void Oncat_DescripcionChanged();
    #endregion
		
		public TbCategoria()
		{
			this._TbProducto = new EntitySet<TbProducto>(new Action<TbProducto>(this.attach_TbProducto), new Action<TbProducto>(this.detach_TbProducto));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cat_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int cat_Id
		{
			get
			{
				return this._cat_Id;
			}
			set
			{
				if ((this._cat_Id != value))
				{
					this.Oncat_IdChanging(value);
					this.SendPropertyChanging();
					this._cat_Id = value;
					this.SendPropertyChanged("cat_Id");
					this.Oncat_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cat_Descripcion", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string cat_Descripcion
		{
			get
			{
				return this._cat_Descripcion;
			}
			set
			{
				if ((this._cat_Descripcion != value))
				{
					this.Oncat_DescripcionChanging(value);
					this.SendPropertyChanging();
					this._cat_Descripcion = value;
					this.SendPropertyChanged("cat_Descripcion");
					this.Oncat_DescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TbCategoria_TbProducto", Storage="_TbProducto", ThisKey="cat_Id", OtherKey="pd_IdCategoria")]
		public EntitySet<TbProducto> TbProducto
		{
			get
			{
				return this._TbProducto;
			}
			set
			{
				this._TbProducto.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TbProducto(TbProducto entity)
		{
			this.SendPropertyChanging();
			entity.TbCategoria = this;
		}
		
		private void detach_TbProducto(TbProducto entity)
		{
			this.SendPropertyChanging();
			entity.TbCategoria = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TbEmpleados")]
	public partial class TbEmpleados : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _em_identificacion;
		
		private System.DateTime _em_fechaNacimiento;
		
		private string _em_nombre;
		
		private string _em_contrasena;
		
		private int _em_tipoId;
		
		private string _em_direccion;
		
		private int _em_cargo;
		
		private string _em_contacto;
		
		private EntitySet<TbMovimiento> _TbMovimiento;
		
		private EntityRef<TbCargo> _TbCargo;
		
		private EntityRef<TbTipoId> _TbTipoId;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onem_identificacionChanging(string value);
    partial void Onem_identificacionChanged();
    partial void Onem_fechaNacimientoChanging(System.DateTime value);
    partial void Onem_fechaNacimientoChanged();
    partial void Onem_nombreChanging(string value);
    partial void Onem_nombreChanged();
    partial void Onem_contrasenaChanging(string value);
    partial void Onem_contrasenaChanged();
    partial void Onem_tipoIdChanging(int value);
    partial void Onem_tipoIdChanged();
    partial void Onem_direccionChanging(string value);
    partial void Onem_direccionChanged();
    partial void Onem_cargoChanging(int value);
    partial void Onem_cargoChanged();
    partial void Onem_contactoChanging(string value);
    partial void Onem_contactoChanged();
    #endregion
		
		public TbEmpleados()
		{
			this._TbMovimiento = new EntitySet<TbMovimiento>(new Action<TbMovimiento>(this.attach_TbMovimiento), new Action<TbMovimiento>(this.detach_TbMovimiento));
			this._TbCargo = default(EntityRef<TbCargo>);
			this._TbTipoId = default(EntityRef<TbTipoId>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_em_identificacion", DbType="VarChar(30) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string em_identificacion
		{
			get
			{
				return this._em_identificacion;
			}
			set
			{
				if ((this._em_identificacion != value))
				{
					this.Onem_identificacionChanging(value);
					this.SendPropertyChanging();
					this._em_identificacion = value;
					this.SendPropertyChanged("em_identificacion");
					this.Onem_identificacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_em_fechaNacimiento", DbType="Date NOT NULL")]
		public System.DateTime em_fechaNacimiento
		{
			get
			{
				return this._em_fechaNacimiento;
			}
			set
			{
				if ((this._em_fechaNacimiento != value))
				{
					this.Onem_fechaNacimientoChanging(value);
					this.SendPropertyChanging();
					this._em_fechaNacimiento = value;
					this.SendPropertyChanged("em_fechaNacimiento");
					this.Onem_fechaNacimientoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_em_nombre", DbType="VarChar(70) NOT NULL", CanBeNull=false)]
		public string em_nombre
		{
			get
			{
				return this._em_nombre;
			}
			set
			{
				if ((this._em_nombre != value))
				{
					this.Onem_nombreChanging(value);
					this.SendPropertyChanging();
					this._em_nombre = value;
					this.SendPropertyChanged("em_nombre");
					this.Onem_nombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_em_contrasena", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string em_contrasena
		{
			get
			{
				return this._em_contrasena;
			}
			set
			{
				if ((this._em_contrasena != value))
				{
					this.Onem_contrasenaChanging(value);
					this.SendPropertyChanging();
					this._em_contrasena = value;
					this.SendPropertyChanged("em_contrasena");
					this.Onem_contrasenaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_em_tipoId", DbType="Int NOT NULL")]
		public int em_tipoId
		{
			get
			{
				return this._em_tipoId;
			}
			set
			{
				if ((this._em_tipoId != value))
				{
					if (this._TbTipoId.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onem_tipoIdChanging(value);
					this.SendPropertyChanging();
					this._em_tipoId = value;
					this.SendPropertyChanged("em_tipoId");
					this.Onem_tipoIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_em_direccion", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string em_direccion
		{
			get
			{
				return this._em_direccion;
			}
			set
			{
				if ((this._em_direccion != value))
				{
					this.Onem_direccionChanging(value);
					this.SendPropertyChanging();
					this._em_direccion = value;
					this.SendPropertyChanged("em_direccion");
					this.Onem_direccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_em_cargo", DbType="Int NOT NULL")]
		public int em_cargo
		{
			get
			{
				return this._em_cargo;
			}
			set
			{
				if ((this._em_cargo != value))
				{
					if (this._TbCargo.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onem_cargoChanging(value);
					this.SendPropertyChanging();
					this._em_cargo = value;
					this.SendPropertyChanged("em_cargo");
					this.Onem_cargoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_em_contacto", DbType="VarChar(60) NOT NULL", CanBeNull=false)]
		public string em_contacto
		{
			get
			{
				return this._em_contacto;
			}
			set
			{
				if ((this._em_contacto != value))
				{
					this.Onem_contactoChanging(value);
					this.SendPropertyChanging();
					this._em_contacto = value;
					this.SendPropertyChanged("em_contacto");
					this.Onem_contactoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TbEmpleados_TbMovimiento", Storage="_TbMovimiento", ThisKey="em_identificacion", OtherKey="mo_IdEmpleado")]
		public EntitySet<TbMovimiento> TbMovimiento
		{
			get
			{
				return this._TbMovimiento;
			}
			set
			{
				this._TbMovimiento.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TbCargo_TbEmpleados", Storage="_TbCargo", ThisKey="em_cargo", OtherKey="ca_Id", IsForeignKey=true)]
		public TbCargo TbCargo
		{
			get
			{
				return this._TbCargo.Entity;
			}
			set
			{
				TbCargo previousValue = this._TbCargo.Entity;
				if (((previousValue != value) 
							|| (this._TbCargo.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TbCargo.Entity = null;
						previousValue.TbEmpleados.Remove(this);
					}
					this._TbCargo.Entity = value;
					if ((value != null))
					{
						value.TbEmpleados.Add(this);
						this._em_cargo = value.ca_Id;
					}
					else
					{
						this._em_cargo = default(int);
					}
					this.SendPropertyChanged("TbCargo");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TbTipoId_TbEmpleados", Storage="_TbTipoId", ThisKey="em_tipoId", OtherKey="tid_Id", IsForeignKey=true)]
		public TbTipoId TbTipoId
		{
			get
			{
				return this._TbTipoId.Entity;
			}
			set
			{
				TbTipoId previousValue = this._TbTipoId.Entity;
				if (((previousValue != value) 
							|| (this._TbTipoId.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TbTipoId.Entity = null;
						previousValue.TbEmpleados.Remove(this);
					}
					this._TbTipoId.Entity = value;
					if ((value != null))
					{
						value.TbEmpleados.Add(this);
						this._em_tipoId = value.tid_Id;
					}
					else
					{
						this._em_tipoId = default(int);
					}
					this.SendPropertyChanged("TbTipoId");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TbMovimiento(TbMovimiento entity)
		{
			this.SendPropertyChanging();
			entity.TbEmpleados = this;
		}
		
		private void detach_TbMovimiento(TbMovimiento entity)
		{
			this.SendPropertyChanging();
			entity.TbEmpleados = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TbMovimiento")]
	public partial class TbMovimiento : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _mo_IdMovimiento;
		
		private System.DateTime _mo_Fecha;
		
		private int _mo_IdProducto;
		
		private int _mo_CantiadProducto;
		
		private string _mo_IdEmpleado;
		
		private string _mo_Ubicacion;
		
		private int _mo_IdTipo;
		
		private int _mo_Conector;
		
		private EntityRef<TbEmpleados> _TbEmpleados;
		
		private EntityRef<TbTipoMovimiento> _TbTipoMovimiento;
		
		private EntityRef<TbProducto> _TbProducto;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onmo_IdMovimientoChanging(int value);
    partial void Onmo_IdMovimientoChanged();
    partial void Onmo_FechaChanging(System.DateTime value);
    partial void Onmo_FechaChanged();
    partial void Onmo_IdProductoChanging(int value);
    partial void Onmo_IdProductoChanged();
    partial void Onmo_CantiadProductoChanging(int value);
    partial void Onmo_CantiadProductoChanged();
    partial void Onmo_IdEmpleadoChanging(string value);
    partial void Onmo_IdEmpleadoChanged();
    partial void Onmo_UbicacionChanging(string value);
    partial void Onmo_UbicacionChanged();
    partial void Onmo_IdTipoChanging(int value);
    partial void Onmo_IdTipoChanged();
    partial void Onmo_ConectorChanging(int value);
    partial void Onmo_ConectorChanged();
    #endregion
		
		public TbMovimiento()
		{
			this._TbEmpleados = default(EntityRef<TbEmpleados>);
			this._TbTipoMovimiento = default(EntityRef<TbTipoMovimiento>);
			this._TbProducto = default(EntityRef<TbProducto>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mo_IdMovimiento", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int mo_IdMovimiento
		{
			get
			{
				return this._mo_IdMovimiento;
			}
			set
			{
				if ((this._mo_IdMovimiento != value))
				{
					this.Onmo_IdMovimientoChanging(value);
					this.SendPropertyChanging();
					this._mo_IdMovimiento = value;
					this.SendPropertyChanged("mo_IdMovimiento");
					this.Onmo_IdMovimientoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mo_Fecha", DbType="Date NOT NULL")]
		public System.DateTime mo_Fecha
		{
			get
			{
				return this._mo_Fecha;
			}
			set
			{
				if ((this._mo_Fecha != value))
				{
					this.Onmo_FechaChanging(value);
					this.SendPropertyChanging();
					this._mo_Fecha = value;
					this.SendPropertyChanged("mo_Fecha");
					this.Onmo_FechaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mo_IdProducto", DbType="Int NOT NULL")]
		public int mo_IdProducto
		{
			get
			{
				return this._mo_IdProducto;
			}
			set
			{
				if ((this._mo_IdProducto != value))
				{
					if (this._TbProducto.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onmo_IdProductoChanging(value);
					this.SendPropertyChanging();
					this._mo_IdProducto = value;
					this.SendPropertyChanged("mo_IdProducto");
					this.Onmo_IdProductoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mo_CantiadProducto", DbType="Int NOT NULL")]
		public int mo_CantiadProducto
		{
			get
			{
				return this._mo_CantiadProducto;
			}
			set
			{
				if ((this._mo_CantiadProducto != value))
				{
					this.Onmo_CantiadProductoChanging(value);
					this.SendPropertyChanging();
					this._mo_CantiadProducto = value;
					this.SendPropertyChanged("mo_CantiadProducto");
					this.Onmo_CantiadProductoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mo_IdEmpleado", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string mo_IdEmpleado
		{
			get
			{
				return this._mo_IdEmpleado;
			}
			set
			{
				if ((this._mo_IdEmpleado != value))
				{
					if (this._TbEmpleados.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onmo_IdEmpleadoChanging(value);
					this.SendPropertyChanging();
					this._mo_IdEmpleado = value;
					this.SendPropertyChanged("mo_IdEmpleado");
					this.Onmo_IdEmpleadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mo_Ubicacion", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string mo_Ubicacion
		{
			get
			{
				return this._mo_Ubicacion;
			}
			set
			{
				if ((this._mo_Ubicacion != value))
				{
					this.Onmo_UbicacionChanging(value);
					this.SendPropertyChanging();
					this._mo_Ubicacion = value;
					this.SendPropertyChanged("mo_Ubicacion");
					this.Onmo_UbicacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mo_IdTipo", DbType="Int NOT NULL")]
		public int mo_IdTipo
		{
			get
			{
				return this._mo_IdTipo;
			}
			set
			{
				if ((this._mo_IdTipo != value))
				{
					if (this._TbTipoMovimiento.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onmo_IdTipoChanging(value);
					this.SendPropertyChanging();
					this._mo_IdTipo = value;
					this.SendPropertyChanged("mo_IdTipo");
					this.Onmo_IdTipoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mo_Conector", DbType="Int NOT NULL")]
		public int mo_Conector
		{
			get
			{
				return this._mo_Conector;
			}
			set
			{
				if ((this._mo_Conector != value))
				{
					this.Onmo_ConectorChanging(value);
					this.SendPropertyChanging();
					this._mo_Conector = value;
					this.SendPropertyChanged("mo_Conector");
					this.Onmo_ConectorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TbEmpleados_TbMovimiento", Storage="_TbEmpleados", ThisKey="mo_IdEmpleado", OtherKey="em_identificacion", IsForeignKey=true)]
		public TbEmpleados TbEmpleados
		{
			get
			{
				return this._TbEmpleados.Entity;
			}
			set
			{
				TbEmpleados previousValue = this._TbEmpleados.Entity;
				if (((previousValue != value) 
							|| (this._TbEmpleados.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TbEmpleados.Entity = null;
						previousValue.TbMovimiento.Remove(this);
					}
					this._TbEmpleados.Entity = value;
					if ((value != null))
					{
						value.TbMovimiento.Add(this);
						this._mo_IdEmpleado = value.em_identificacion;
					}
					else
					{
						this._mo_IdEmpleado = default(string);
					}
					this.SendPropertyChanged("TbEmpleados");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TbTipoMovimiento_TbMovimiento", Storage="_TbTipoMovimiento", ThisKey="mo_IdTipo", OtherKey="Tmo_IdTipoMovimiento", IsForeignKey=true)]
		public TbTipoMovimiento TbTipoMovimiento
		{
			get
			{
				return this._TbTipoMovimiento.Entity;
			}
			set
			{
				TbTipoMovimiento previousValue = this._TbTipoMovimiento.Entity;
				if (((previousValue != value) 
							|| (this._TbTipoMovimiento.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TbTipoMovimiento.Entity = null;
						previousValue.TbMovimiento.Remove(this);
					}
					this._TbTipoMovimiento.Entity = value;
					if ((value != null))
					{
						value.TbMovimiento.Add(this);
						this._mo_IdTipo = value.Tmo_IdTipoMovimiento;
					}
					else
					{
						this._mo_IdTipo = default(int);
					}
					this.SendPropertyChanged("TbTipoMovimiento");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TbProducto_TbMovimiento", Storage="_TbProducto", ThisKey="mo_IdProducto", OtherKey="pd_IdProducto", IsForeignKey=true)]
		public TbProducto TbProducto
		{
			get
			{
				return this._TbProducto.Entity;
			}
			set
			{
				TbProducto previousValue = this._TbProducto.Entity;
				if (((previousValue != value) 
							|| (this._TbProducto.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TbProducto.Entity = null;
						previousValue.TbMovimiento.Remove(this);
					}
					this._TbProducto.Entity = value;
					if ((value != null))
					{
						value.TbMovimiento.Add(this);
						this._mo_IdProducto = value.pd_IdProducto;
					}
					else
					{
						this._mo_IdProducto = default(int);
					}
					this.SendPropertyChanged("TbProducto");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TbOrdenCompra")]
	public partial class TbOrdenCompra
	{
		
		private int _op_IdOrdenPedido;
		
		private decimal _op_IdPrecioCompra;
		
		public TbOrdenCompra()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_op_IdOrdenPedido", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int op_IdOrdenPedido
		{
			get
			{
				return this._op_IdOrdenPedido;
			}
			set
			{
				if ((this._op_IdOrdenPedido != value))
				{
					this._op_IdOrdenPedido = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_op_IdPrecioCompra", DbType="Money NOT NULL")]
		public decimal op_IdPrecioCompra
		{
			get
			{
				return this._op_IdPrecioCompra;
			}
			set
			{
				if ((this._op_IdPrecioCompra != value))
				{
					this._op_IdPrecioCompra = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TbProducto")]
	public partial class TbProducto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _pd_IdProducto;
		
		private string _pd_Nombre;
		
		private int _pd_Cantidad;
		
		private decimal _pd_Precio;
		
		private int _pd_Unidades;
		
		private int _pd_StockMin;
		
		private int _pd_StockMax;
		
		private string _pd_CantidadXUnidad;
		
		private int _pd_IdCategoria;
		
		private EntitySet<TbMovimiento> _TbMovimiento;
		
		private EntityRef<TbCategoria> _TbCategoria;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onpd_IdProductoChanging(int value);
    partial void Onpd_IdProductoChanged();
    partial void Onpd_NombreChanging(string value);
    partial void Onpd_NombreChanged();
    partial void Onpd_CantidadChanging(int value);
    partial void Onpd_CantidadChanged();
    partial void Onpd_PrecioChanging(decimal value);
    partial void Onpd_PrecioChanged();
    partial void Onpd_UnidadesChanging(int value);
    partial void Onpd_UnidadesChanged();
    partial void Onpd_StockMinChanging(int value);
    partial void Onpd_StockMinChanged();
    partial void Onpd_StockMaxChanging(int value);
    partial void Onpd_StockMaxChanged();
    partial void Onpd_CantidadXUnidadChanging(string value);
    partial void Onpd_CantidadXUnidadChanged();
    partial void Onpd_IdCategoriaChanging(int value);
    partial void Onpd_IdCategoriaChanged();
    #endregion
		
		public TbProducto()
		{
			this._TbMovimiento = new EntitySet<TbMovimiento>(new Action<TbMovimiento>(this.attach_TbMovimiento), new Action<TbMovimiento>(this.detach_TbMovimiento));
			this._TbCategoria = default(EntityRef<TbCategoria>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pd_IdProducto", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int pd_IdProducto
		{
			get
			{
				return this._pd_IdProducto;
			}
			set
			{
				if ((this._pd_IdProducto != value))
				{
					this.Onpd_IdProductoChanging(value);
					this.SendPropertyChanging();
					this._pd_IdProducto = value;
					this.SendPropertyChanged("pd_IdProducto");
					this.Onpd_IdProductoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pd_Nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string pd_Nombre
		{
			get
			{
				return this._pd_Nombre;
			}
			set
			{
				if ((this._pd_Nombre != value))
				{
					this.Onpd_NombreChanging(value);
					this.SendPropertyChanging();
					this._pd_Nombre = value;
					this.SendPropertyChanged("pd_Nombre");
					this.Onpd_NombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pd_Cantidad", DbType="Int NOT NULL")]
		public int pd_Cantidad
		{
			get
			{
				return this._pd_Cantidad;
			}
			set
			{
				if ((this._pd_Cantidad != value))
				{
					this.Onpd_CantidadChanging(value);
					this.SendPropertyChanging();
					this._pd_Cantidad = value;
					this.SendPropertyChanged("pd_Cantidad");
					this.Onpd_CantidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pd_Precio", DbType="Money NOT NULL")]
		public decimal pd_Precio
		{
			get
			{
				return this._pd_Precio;
			}
			set
			{
				if ((this._pd_Precio != value))
				{
					this.Onpd_PrecioChanging(value);
					this.SendPropertyChanging();
					this._pd_Precio = value;
					this.SendPropertyChanged("pd_Precio");
					this.Onpd_PrecioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pd_Unidades", DbType="Int NOT NULL")]
		public int pd_Unidades
		{
			get
			{
				return this._pd_Unidades;
			}
			set
			{
				if ((this._pd_Unidades != value))
				{
					this.Onpd_UnidadesChanging(value);
					this.SendPropertyChanging();
					this._pd_Unidades = value;
					this.SendPropertyChanged("pd_Unidades");
					this.Onpd_UnidadesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pd_StockMin", DbType="Int NOT NULL")]
		public int pd_StockMin
		{
			get
			{
				return this._pd_StockMin;
			}
			set
			{
				if ((this._pd_StockMin != value))
				{
					this.Onpd_StockMinChanging(value);
					this.SendPropertyChanging();
					this._pd_StockMin = value;
					this.SendPropertyChanged("pd_StockMin");
					this.Onpd_StockMinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pd_StockMax", DbType="Int NOT NULL")]
		public int pd_StockMax
		{
			get
			{
				return this._pd_StockMax;
			}
			set
			{
				if ((this._pd_StockMax != value))
				{
					this.Onpd_StockMaxChanging(value);
					this.SendPropertyChanging();
					this._pd_StockMax = value;
					this.SendPropertyChanged("pd_StockMax");
					this.Onpd_StockMaxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pd_CantidadXUnidad", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string pd_CantidadXUnidad
		{
			get
			{
				return this._pd_CantidadXUnidad;
			}
			set
			{
				if ((this._pd_CantidadXUnidad != value))
				{
					this.Onpd_CantidadXUnidadChanging(value);
					this.SendPropertyChanging();
					this._pd_CantidadXUnidad = value;
					this.SendPropertyChanged("pd_CantidadXUnidad");
					this.Onpd_CantidadXUnidadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pd_IdCategoria", DbType="Int NOT NULL")]
		public int pd_IdCategoria
		{
			get
			{
				return this._pd_IdCategoria;
			}
			set
			{
				if ((this._pd_IdCategoria != value))
				{
					if (this._TbCategoria.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onpd_IdCategoriaChanging(value);
					this.SendPropertyChanging();
					this._pd_IdCategoria = value;
					this.SendPropertyChanged("pd_IdCategoria");
					this.Onpd_IdCategoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TbProducto_TbMovimiento", Storage="_TbMovimiento", ThisKey="pd_IdProducto", OtherKey="mo_IdProducto")]
		public EntitySet<TbMovimiento> TbMovimiento
		{
			get
			{
				return this._TbMovimiento;
			}
			set
			{
				this._TbMovimiento.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TbCategoria_TbProducto", Storage="_TbCategoria", ThisKey="pd_IdCategoria", OtherKey="cat_Id", IsForeignKey=true)]
		public TbCategoria TbCategoria
		{
			get
			{
				return this._TbCategoria.Entity;
			}
			set
			{
				TbCategoria previousValue = this._TbCategoria.Entity;
				if (((previousValue != value) 
							|| (this._TbCategoria.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TbCategoria.Entity = null;
						previousValue.TbProducto.Remove(this);
					}
					this._TbCategoria.Entity = value;
					if ((value != null))
					{
						value.TbProducto.Add(this);
						this._pd_IdCategoria = value.cat_Id;
					}
					else
					{
						this._pd_IdCategoria = default(int);
					}
					this.SendPropertyChanged("TbCategoria");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TbMovimiento(TbMovimiento entity)
		{
			this.SendPropertyChanging();
			entity.TbProducto = this;
		}
		
		private void detach_TbMovimiento(TbMovimiento entity)
		{
			this.SendPropertyChanging();
			entity.TbProducto = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TbProveedor")]
	public partial class TbProveedor
	{
		
		private int _pv_IdProveedor;
		
		private string _pv_Nombre;
		
		private string _pv_Contacto;
		
		private string _pv_Direccion;
		
		public TbProveedor()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pv_IdProveedor", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int pv_IdProveedor
		{
			get
			{
				return this._pv_IdProveedor;
			}
			set
			{
				if ((this._pv_IdProveedor != value))
				{
					this._pv_IdProveedor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pv_Nombre", DbType="VarChar(70) NOT NULL", CanBeNull=false)]
		public string pv_Nombre
		{
			get
			{
				return this._pv_Nombre;
			}
			set
			{
				if ((this._pv_Nombre != value))
				{
					this._pv_Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pv_Contacto", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string pv_Contacto
		{
			get
			{
				return this._pv_Contacto;
			}
			set
			{
				if ((this._pv_Contacto != value))
				{
					this._pv_Contacto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pv_Direccion", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string pv_Direccion
		{
			get
			{
				return this._pv_Direccion;
			}
			set
			{
				if ((this._pv_Direccion != value))
				{
					this._pv_Direccion = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TbTipoId")]
	public partial class TbTipoId : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _tid_Id;
		
		private string _tid_Nombre;
		
		private string _tid_Descripcion;
		
		private EntitySet<TbEmpleados> _TbEmpleados;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ontid_IdChanging(int value);
    partial void Ontid_IdChanged();
    partial void Ontid_NombreChanging(string value);
    partial void Ontid_NombreChanged();
    partial void Ontid_DescripcionChanging(string value);
    partial void Ontid_DescripcionChanged();
    #endregion
		
		public TbTipoId()
		{
			this._TbEmpleados = new EntitySet<TbEmpleados>(new Action<TbEmpleados>(this.attach_TbEmpleados), new Action<TbEmpleados>(this.detach_TbEmpleados));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tid_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int tid_Id
		{
			get
			{
				return this._tid_Id;
			}
			set
			{
				if ((this._tid_Id != value))
				{
					this.Ontid_IdChanging(value);
					this.SendPropertyChanging();
					this._tid_Id = value;
					this.SendPropertyChanged("tid_Id");
					this.Ontid_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tid_Nombre", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string tid_Nombre
		{
			get
			{
				return this._tid_Nombre;
			}
			set
			{
				if ((this._tid_Nombre != value))
				{
					this.Ontid_NombreChanging(value);
					this.SendPropertyChanging();
					this._tid_Nombre = value;
					this.SendPropertyChanged("tid_Nombre");
					this.Ontid_NombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tid_Descripcion", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string tid_Descripcion
		{
			get
			{
				return this._tid_Descripcion;
			}
			set
			{
				if ((this._tid_Descripcion != value))
				{
					this.Ontid_DescripcionChanging(value);
					this.SendPropertyChanging();
					this._tid_Descripcion = value;
					this.SendPropertyChanged("tid_Descripcion");
					this.Ontid_DescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TbTipoId_TbEmpleados", Storage="_TbEmpleados", ThisKey="tid_Id", OtherKey="em_tipoId")]
		public EntitySet<TbEmpleados> TbEmpleados
		{
			get
			{
				return this._TbEmpleados;
			}
			set
			{
				this._TbEmpleados.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TbEmpleados(TbEmpleados entity)
		{
			this.SendPropertyChanging();
			entity.TbTipoId = this;
		}
		
		private void detach_TbEmpleados(TbEmpleados entity)
		{
			this.SendPropertyChanging();
			entity.TbTipoId = null;
		}
	}
	
	public partial class accederEmpleadoResult
	{
		
		private string _Identificacion;
		
		private System.DateTime _Fecha_Nacimiento;
		
		private string _Nombre;
		
		private string _Contrasena;
		
		private string _Tipo_Documento;
		
		private string _Direccion;
		
		private string _Cargo;
		
		private string _Telefono_de_Contacto;
		
		public accederEmpleadoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Identificacion", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string Identificacion
		{
			get
			{
				return this._Identificacion;
			}
			set
			{
				if ((this._Identificacion != value))
				{
					this._Identificacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Fecha Nacimiento]", Storage="_Fecha_Nacimiento", DbType="Date NOT NULL")]
		public System.DateTime Fecha_Nacimiento
		{
			get
			{
				return this._Fecha_Nacimiento;
			}
			set
			{
				if ((this._Fecha_Nacimiento != value))
				{
					this._Fecha_Nacimiento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(70) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contrasena", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Contrasena
		{
			get
			{
				return this._Contrasena;
			}
			set
			{
				if ((this._Contrasena != value))
				{
					this._Contrasena = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Tipo Documento]", Storage="_Tipo_Documento", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string Tipo_Documento
		{
			get
			{
				return this._Tipo_Documento;
			}
			set
			{
				if ((this._Tipo_Documento != value))
				{
					this._Tipo_Documento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direccion", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Direccion
		{
			get
			{
				return this._Direccion;
			}
			set
			{
				if ((this._Direccion != value))
				{
					this._Direccion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cargo", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string Cargo
		{
			get
			{
				return this._Cargo;
			}
			set
			{
				if ((this._Cargo != value))
				{
					this._Cargo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Telefono de Contacto]", Storage="_Telefono_de_Contacto", DbType="VarChar(60) NOT NULL", CanBeNull=false)]
		public string Telefono_de_Contacto
		{
			get
			{
				return this._Telefono_de_Contacto;
			}
			set
			{
				if ((this._Telefono_de_Contacto != value))
				{
					this._Telefono_de_Contacto = value;
				}
			}
		}
	}
	
	public partial class verEmpleadosResult
	{
		
		private string _Identificacion;
		
		private System.DateTime _Fecha_Nacimiento;
		
		private string _Nombre;
		
		private string _Contrasena;
		
		private string _Tipo_Documento;
		
		private string _Direccion;
		
		private string _Cargo;
		
		private string _Telefono_de_Contacto;
		
		public verEmpleadosResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Identificacion", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string Identificacion
		{
			get
			{
				return this._Identificacion;
			}
			set
			{
				if ((this._Identificacion != value))
				{
					this._Identificacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Fecha Nacimiento]", Storage="_Fecha_Nacimiento", DbType="Date NOT NULL")]
		public System.DateTime Fecha_Nacimiento
		{
			get
			{
				return this._Fecha_Nacimiento;
			}
			set
			{
				if ((this._Fecha_Nacimiento != value))
				{
					this._Fecha_Nacimiento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(70) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contrasena", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Contrasena
		{
			get
			{
				return this._Contrasena;
			}
			set
			{
				if ((this._Contrasena != value))
				{
					this._Contrasena = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Tipo Documento]", Storage="_Tipo_Documento", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string Tipo_Documento
		{
			get
			{
				return this._Tipo_Documento;
			}
			set
			{
				if ((this._Tipo_Documento != value))
				{
					this._Tipo_Documento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direccion", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Direccion
		{
			get
			{
				return this._Direccion;
			}
			set
			{
				if ((this._Direccion != value))
				{
					this._Direccion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cargo", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string Cargo
		{
			get
			{
				return this._Cargo;
			}
			set
			{
				if ((this._Cargo != value))
				{
					this._Cargo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Telefono de Contacto]", Storage="_Telefono_de_Contacto", DbType="VarChar(60) NOT NULL", CanBeNull=false)]
		public string Telefono_de_Contacto
		{
			get
			{
				return this._Telefono_de_Contacto;
			}
			set
			{
				if ((this._Telefono_de_Contacto != value))
				{
					this._Telefono_de_Contacto = value;
				}
			}
		}
	}
	
	public partial class listar_MovimientosResult
	{
		
		private System.DateTime _mo_Fecha;
		
		private int _mo_IdProducto;
		
		private int _mo_CantiadProducto;
		
		private string _mo_IdEmpleado;
		
		private string _mo_Ubicacion;
		
		private int _mo_IdTipo;
		
		private int _mo_Conector;
		
		public listar_MovimientosResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mo_Fecha", DbType="Date NOT NULL")]
		public System.DateTime mo_Fecha
		{
			get
			{
				return this._mo_Fecha;
			}
			set
			{
				if ((this._mo_Fecha != value))
				{
					this._mo_Fecha = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mo_IdProducto", DbType="Int NOT NULL")]
		public int mo_IdProducto
		{
			get
			{
				return this._mo_IdProducto;
			}
			set
			{
				if ((this._mo_IdProducto != value))
				{
					this._mo_IdProducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mo_CantiadProducto", DbType="Int NOT NULL")]
		public int mo_CantiadProducto
		{
			get
			{
				return this._mo_CantiadProducto;
			}
			set
			{
				if ((this._mo_CantiadProducto != value))
				{
					this._mo_CantiadProducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mo_IdEmpleado", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string mo_IdEmpleado
		{
			get
			{
				return this._mo_IdEmpleado;
			}
			set
			{
				if ((this._mo_IdEmpleado != value))
				{
					this._mo_IdEmpleado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mo_Ubicacion", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string mo_Ubicacion
		{
			get
			{
				return this._mo_Ubicacion;
			}
			set
			{
				if ((this._mo_Ubicacion != value))
				{
					this._mo_Ubicacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mo_IdTipo", DbType="Int NOT NULL")]
		public int mo_IdTipo
		{
			get
			{
				return this._mo_IdTipo;
			}
			set
			{
				if ((this._mo_IdTipo != value))
				{
					this._mo_IdTipo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mo_Conector", DbType="Int NOT NULL")]
		public int mo_Conector
		{
			get
			{
				return this._mo_Conector;
			}
			set
			{
				if ((this._mo_Conector != value))
				{
					this._mo_Conector = value;
				}
			}
		}
	}
	
	public partial class listarCatgoriaResult
	{
		
		private int _cat_Id;
		
		private string _cat_Descripcion;
		
		public listarCatgoriaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cat_Id", DbType="Int NOT NULL")]
		public int cat_Id
		{
			get
			{
				return this._cat_Id;
			}
			set
			{
				if ((this._cat_Id != value))
				{
					this._cat_Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cat_Descripcion", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string cat_Descripcion
		{
			get
			{
				return this._cat_Descripcion;
			}
			set
			{
				if ((this._cat_Descripcion != value))
				{
					this._cat_Descripcion = value;
				}
			}
		}
	}
	
	public partial class listarOrdenCompraResult
	{
		
		private int _op_IdOrdenPedido;
		
		private decimal _op_IdPrecioCompra;
		
		public listarOrdenCompraResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_op_IdOrdenPedido", DbType="Int NOT NULL")]
		public int op_IdOrdenPedido
		{
			get
			{
				return this._op_IdOrdenPedido;
			}
			set
			{
				if ((this._op_IdOrdenPedido != value))
				{
					this._op_IdOrdenPedido = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_op_IdPrecioCompra", DbType="Money NOT NULL")]
		public decimal op_IdPrecioCompra
		{
			get
			{
				return this._op_IdPrecioCompra;
			}
			set
			{
				if ((this._op_IdPrecioCompra != value))
				{
					this._op_IdPrecioCompra = value;
				}
			}
		}
	}
	
	public partial class listarProductosResult
	{
		
		private int _pd_IdProducto;
		
		private string _pd_Nombre;
		
		private int _pd_Cantidad;
		
		private decimal _pd_Precio;
		
		private int _pd_Unidades;
		
		private int _pd_StockMin;
		
		private int _pd_StockMax;
		
		private string _pd_CantidadXUnidad;
		
		private string _cat_Descripcion;
		
		public listarProductosResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pd_IdProducto", DbType="Int NOT NULL")]
		public int pd_IdProducto
		{
			get
			{
				return this._pd_IdProducto;
			}
			set
			{
				if ((this._pd_IdProducto != value))
				{
					this._pd_IdProducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pd_Nombre", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string pd_Nombre
		{
			get
			{
				return this._pd_Nombre;
			}
			set
			{
				if ((this._pd_Nombre != value))
				{
					this._pd_Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pd_Cantidad", DbType="Int NOT NULL")]
		public int pd_Cantidad
		{
			get
			{
				return this._pd_Cantidad;
			}
			set
			{
				if ((this._pd_Cantidad != value))
				{
					this._pd_Cantidad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pd_Precio", DbType="Money NOT NULL")]
		public decimal pd_Precio
		{
			get
			{
				return this._pd_Precio;
			}
			set
			{
				if ((this._pd_Precio != value))
				{
					this._pd_Precio = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pd_Unidades", DbType="Int NOT NULL")]
		public int pd_Unidades
		{
			get
			{
				return this._pd_Unidades;
			}
			set
			{
				if ((this._pd_Unidades != value))
				{
					this._pd_Unidades = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pd_StockMin", DbType="Int NOT NULL")]
		public int pd_StockMin
		{
			get
			{
				return this._pd_StockMin;
			}
			set
			{
				if ((this._pd_StockMin != value))
				{
					this._pd_StockMin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pd_StockMax", DbType="Int NOT NULL")]
		public int pd_StockMax
		{
			get
			{
				return this._pd_StockMax;
			}
			set
			{
				if ((this._pd_StockMax != value))
				{
					this._pd_StockMax = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pd_CantidadXUnidad", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string pd_CantidadXUnidad
		{
			get
			{
				return this._pd_CantidadXUnidad;
			}
			set
			{
				if ((this._pd_CantidadXUnidad != value))
				{
					this._pd_CantidadXUnidad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cat_Descripcion", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string cat_Descripcion
		{
			get
			{
				return this._cat_Descripcion;
			}
			set
			{
				if ((this._cat_Descripcion != value))
				{
					this._cat_Descripcion = value;
				}
			}
		}
	}
	
	public partial class listarProveedorResult
	{
		
		private int _pv_IdProveedor;
		
		private string _pv_Nombre;
		
		private string _pv_Contacto;
		
		private string _pv_Direccion;
		
		public listarProveedorResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pv_IdProveedor", DbType="Int NOT NULL")]
		public int pv_IdProveedor
		{
			get
			{
				return this._pv_IdProveedor;
			}
			set
			{
				if ((this._pv_IdProveedor != value))
				{
					this._pv_IdProveedor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pv_Nombre", DbType="VarChar(70) NOT NULL", CanBeNull=false)]
		public string pv_Nombre
		{
			get
			{
				return this._pv_Nombre;
			}
			set
			{
				if ((this._pv_Nombre != value))
				{
					this._pv_Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pv_Contacto", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string pv_Contacto
		{
			get
			{
				return this._pv_Contacto;
			}
			set
			{
				if ((this._pv_Contacto != value))
				{
					this._pv_Contacto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pv_Direccion", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string pv_Direccion
		{
			get
			{
				return this._pv_Direccion;
			}
			set
			{
				if ((this._pv_Direccion != value))
				{
					this._pv_Direccion = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
