<?xml version="1.0" encoding="utf-8"?><Database Name="outinDB" Class="OutInDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-A1PQ06J;Initial Catalog=outinDB;Integrated Security=True" SettingsObjectName="OutInDB.Properties.Settings" SettingsPropertyName="outinDBConnectionString3" Provider="System.Data.SqlClient" />
  <Table Name="dbo.TbCargo" Member="TbCargo">
    <Type Name="TbCargo">
      <Column Name="ca_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ca_Descripcion" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Association Name="TbCargo_TbEmpleados" Member="TbEmpleados" ThisKey="ca_Id" OtherKey="em_cargo" Type="TbEmpleados" />
    </Type>
  </Table>
  <Table Name="dbo.TbTipoMovimiento" Member="TbTipoMovimiento">
    <Type Name="TbTipoMovimiento">
      <Column Name="Tmo_IdTipoMovimiento" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Tmo_Nombre" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
      <Association Name="TbTipoMovimiento_TbMovimiento" Member="TbMovimiento" ThisKey="Tmo_IdTipoMovimiento" OtherKey="mo_IdTipo" Type="TbMovimiento" />
    </Type>
  </Table>
  <Table Name="dbo.TbCategoria" Member="TbCategoria">
    <Type Name="TbCategoria">
      <Column Name="cat_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="cat_Descripcion" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="TbCategoria_TbProducto" Member="TbProducto" ThisKey="cat_Id" OtherKey="pd_IdCategoria" Type="TbProducto" />
    </Type>
  </Table>
  <Table Name="dbo.TbEmpleados" Member="TbEmpleados">
    <Type Name="TbEmpleados">
      <Column Name="em_identificacion" Type="System.String" DbType="VarChar(30) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="em_fechaNacimiento" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="em_nombre" Type="System.String" DbType="VarChar(70) NOT NULL" CanBeNull="false" />
      <Column Name="em_contrasena" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="em_tipoId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="em_direccion" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="em_cargo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="em_contacto" Type="System.String" DbType="VarChar(60) NOT NULL" CanBeNull="false" />
      <Association Name="TbEmpleados_TbMovimiento" Member="TbMovimiento" ThisKey="em_identificacion" OtherKey="mo_IdEmpleado" Type="TbMovimiento" />
      <Association Name="TbCargo_TbEmpleados" Member="TbCargo" ThisKey="em_cargo" OtherKey="ca_Id" Type="TbCargo" IsForeignKey="true" />
      <Association Name="TbTipoId_TbEmpleados" Member="TbTipoId" ThisKey="em_tipoId" OtherKey="tid_Id" Type="TbTipoId" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TbMovimiento" Member="TbMovimiento">
    <Type Name="TbMovimiento">
      <Column Name="mo_IdMovimiento" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="mo_Fecha" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="mo_IdProducto" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="mo_CantiadProducto" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="mo_IdEmpleado" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="mo_Ubicacion" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="mo_IdTipo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="mo_Conector" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="TbEmpleados_TbMovimiento" Member="TbEmpleados" ThisKey="mo_IdEmpleado" OtherKey="em_identificacion" Type="TbEmpleados" IsForeignKey="true" />
      <Association Name="TbTipoMovimiento_TbMovimiento" Member="TbTipoMovimiento" ThisKey="mo_IdTipo" OtherKey="Tmo_IdTipoMovimiento" Type="TbTipoMovimiento" IsForeignKey="true" />
      <Association Name="TbProducto_TbMovimiento" Member="TbProducto" ThisKey="mo_IdProducto" OtherKey="pd_IdProducto" Type="TbProducto" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TbOrdenCompra" Member="TbOrdenCompra">
    <Type Name="TbOrdenCompra">
      <Column Name="op_IdOrdenPedido" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="op_IdPrecioCompra" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.TbProducto" Member="TbProducto">
    <Type Name="TbProducto">
      <Column Name="pd_IdProducto" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="pd_Nombre" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="pd_Cantidad" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="pd_Precio" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="pd_Unidades" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="pd_StockMin" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="pd_StockMax" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="pd_CantidadXUnidad" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="pd_IdCategoria" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="TbProducto_TbMovimiento" Member="TbMovimiento" ThisKey="pd_IdProducto" OtherKey="mo_IdProducto" Type="TbMovimiento" />
      <Association Name="TbCategoria_TbProducto" Member="TbCategoria" ThisKey="pd_IdCategoria" OtherKey="cat_Id" Type="TbCategoria" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TbProveedor" Member="TbProveedor">
    <Type Name="TbProveedor">
      <Column Name="pv_IdProveedor" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="pv_Nombre" Type="System.String" DbType="VarChar(70) NOT NULL" CanBeNull="false" />
      <Column Name="pv_Contacto" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="pv_Direccion" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.TbTipoId" Member="TbTipoId">
    <Type Name="TbTipoId">
      <Column Name="tid_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="tid_Nombre" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="tid_Descripcion" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Association Name="TbTipoId_TbEmpleados" Member="TbEmpleados" ThisKey="tid_Id" OtherKey="em_tipoId" Type="TbEmpleados" />
    </Type>
  </Table>
  <Function Name="dbo.accederEmpleado" Method="accederEmpleado">
    <Parameter Name="usuario" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="contrasena" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="accederEmpleadoResult">
      <Column Name="Identificacion" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="[Fecha Nacimiento]" Member="Fecha_Nacimiento" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(70) NOT NULL" CanBeNull="false" />
      <Column Name="Contrasena" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="[Tipo Documento]" Member="Tipo_Documento" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="Direccion" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Cargo" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="[Telefono de Contacto]" Member="Telefono_de_Contacto" Type="System.String" DbType="VarChar(60) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.verEmpleados" Method="verEmpleados">
    <ElementType Name="verEmpleadosResult">
      <Column Name="Identificacion" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="[Fecha Nacimiento]" Member="Fecha_Nacimiento" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(70) NOT NULL" CanBeNull="false" />
      <Column Name="Contrasena" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="[Tipo Documento]" Member="Tipo_Documento" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="Direccion" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Cargo" Type="System.String" DbType="VarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="[Telefono de Contacto]" Member="Telefono_de_Contacto" Type="System.String" DbType="VarChar(60) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.crearCatgoria" Method="crearCatgoria">
    <Parameter Name="des" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.crearProducto" Method="crearProducto">
    <Parameter Name="nombre" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="cantidad" Type="System.Int32" DbType="Int" />
    <Parameter Name="Precio" Parameter="precio" Type="System.Decimal" DbType="Money" />
    <Parameter Name="Unidades" Parameter="unidades" Type="System.Int32" DbType="Int" />
    <Parameter Name="sMin" Type="System.Int32" DbType="Int" />
    <Parameter Name="sMax" Type="System.Int32" DbType="Int" />
    <Parameter Name="cantXunidad" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Cat" Parameter="cat" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.eliminarCategoria" Method="eliminarCategoria">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.eliminarEmpleado" Method="eliminarEmpleado">
    <Parameter Name="id" Type="System.String" DbType="VarChar(30)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.eliminarProducto" Method="eliminarProducto">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.eliminarProveedor" Method="eliminarProveedor">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Insertar_Movimientos" Method="Insertar_Movimientos">
    <Parameter Name="fecha" Type="System.DateTime" DbType="Date" />
    <Parameter Name="prod" Type="System.Int32" DbType="Int" />
    <Parameter Name="cantP" Type="System.Int32" DbType="Int" />
    <Parameter Name="Emple" Parameter="emple" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="Ubicac" Parameter="ubicac" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="tipo" Type="System.Int32" DbType="Int" />
    <Parameter Name="conec" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.insertarOrdenCompra" Method="insertarOrdenCompra">
    <Parameter Name="moFecha" Type="System.DateTime" DbType="Date" />
    <Parameter Name="moProducto" Type="System.Int32" DbType="Int" />
    <Parameter Name="moCnat" Type="System.Int32" DbType="Int" />
    <Parameter Name="moEmp" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="moUbi" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="moTipo" Type="System.Int32" DbType="Int" />
    <Parameter Name="Prec" Parameter="prec" Type="System.Decimal" DbType="Money" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.InsertarProveedor" Method="InsertarProveedor">
    <Parameter Name="Nombre" Parameter="nombre" Type="System.String" DbType="VarChar(70)" />
    <Parameter Name="Contacto" Parameter="contacto" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Direccion" Parameter="direccion" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.listar_Movimientos" Method="listar_Movimientos">
    <ElementType Name="listar_MovimientosResult">
      <Column Name="mo_Fecha" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="mo_IdProducto" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="mo_CantiadProducto" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="mo_IdEmpleado" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="mo_Ubicacion" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="mo_IdTipo" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="mo_Conector" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.listarCatgoria" Method="listarCatgoria">
    <ElementType Name="listarCatgoriaResult">
      <Column Name="cat_Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="cat_Descripcion" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.listarOrdenCompra" Method="listarOrdenCompra">
    <ElementType Name="listarOrdenCompraResult">
      <Column Name="op_IdOrdenPedido" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="op_IdPrecioCompra" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.listarProductos" Method="listarProductos">
    <ElementType Name="listarProductosResult">
      <Column Name="pd_IdProducto" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="pd_Nombre" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="pd_Cantidad" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="pd_Precio" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="pd_Unidades" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="pd_StockMin" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="pd_StockMax" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="pd_CantidadXUnidad" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="cat_Descripcion" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.listarProveedor" Method="listarProveedor">
    <ElementType Name="listarProveedorResult">
      <Column Name="pv_IdProveedor" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="pv_Nombre" Type="System.String" DbType="VarChar(70) NOT NULL" CanBeNull="false" />
      <Column Name="pv_Contacto" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="pv_Direccion" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.registrarEmpleado" Method="registrarEmpleado">
    <Parameter Name="id" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="nacimiento" Type="System.DateTime" DbType="Date" />
    <Parameter Name="nombre" Type="System.String" DbType="VarChar(70)" />
    <Parameter Name="contrasena" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="tipo" Type="System.Int32" DbType="Int" />
    <Parameter Name="dir" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="cargo" Type="System.Int32" DbType="Int" />
    <Parameter Name="telefono" Type="System.String" DbType="VarChar(60)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.insertarventa" Method="insertarventa">
    <Parameter Name="moFecha" Type="System.DateTime" DbType="Date" />
    <Parameter Name="moProducto" Type="System.Int32" DbType="Int" />
    <Parameter Name="moCnat" Type="System.Int32" DbType="Int" />
    <Parameter Name="moEmp" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="moUbi" Type="System.String" DbType="VarChar(10)" />
    <Parameter Name="moTipo" Type="System.Int32" DbType="Int" />
    <Parameter Name="Prec" Parameter="prec" Type="System.Decimal" DbType="Money" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.listarventa" Method="listarventa">
    <ElementType Name="listarventaResult">
      <Column Name="ve_idventa" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ve_PrecioVenta" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.seleccionarproducto" Method="seleccionarproducto">
    <Parameter Name="nombre" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="seleccionarproductoResult">
      <Column Name="pd_IdProducto" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="pd_Nombre" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="pd_Precio" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.seleccionarproductoxcod" Method="seleccionarproductoxcod">
    <Parameter Name="cod" Type="System.Int32" DbType="Int" />
    <ElementType Name="seleccionarproductoxcodResult">
      <Column Name="pd_IdProducto" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="pd_Nombre" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="pd_Precio" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>