#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OutInDB
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="OutInDb")]
	public partial class OutInDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertTbCargo(TbCargo instance);
    partial void UpdateTbCargo(TbCargo instance);
    partial void DeleteTbCargo(TbCargo instance);
    partial void InsertTbEmpleados(TbEmpleados instance);
    partial void UpdateTbEmpleados(TbEmpleados instance);
    partial void DeleteTbEmpleados(TbEmpleados instance);
    partial void InsertTbTipoId(TbTipoId instance);
    partial void UpdateTbTipoId(TbTipoId instance);
    partial void DeleteTbTipoId(TbTipoId instance);
    #endregion
		
		public OutInDBDataContext() : 
				base(global::OutInDB.Properties.Settings.Default.OutInDbConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public OutInDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OutInDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OutInDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OutInDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TbCargo> TbCargo
		{
			get
			{
				return this.GetTable<TbCargo>();
			}
		}
		
		public System.Data.Linq.Table<TbEmpleados> TbEmpleados
		{
			get
			{
				return this.GetTable<TbEmpleados>();
			}
		}
		
		public System.Data.Linq.Table<TbTipoId> TbTipoId
		{
			get
			{
				return this.GetTable<TbTipoId>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.verEmpleados")]
		public ISingleResult<verEmpleadosResult> verEmpleados()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<verEmpleadosResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.accederEmpleado")]
		public ISingleResult<accederEmpleadoResult> accederEmpleado([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(30)")] string usuario, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string contrasena)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), usuario, contrasena);
			return ((ISingleResult<accederEmpleadoResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TbCargo")]
	public partial class TbCargo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ca_Id;
		
		private string _ca_Descripcion;
		
		private EntitySet<TbEmpleados> _TbEmpleados;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onca_IdChanging(int value);
    partial void Onca_IdChanged();
    partial void Onca_DescripcionChanging(string value);
    partial void Onca_DescripcionChanged();
    #endregion
		
		public TbCargo()
		{
			this._TbEmpleados = new EntitySet<TbEmpleados>(new Action<TbEmpleados>(this.attach_TbEmpleados), new Action<TbEmpleados>(this.detach_TbEmpleados));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ca_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ca_Id
		{
			get
			{
				return this._ca_Id;
			}
			set
			{
				if ((this._ca_Id != value))
				{
					this.Onca_IdChanging(value);
					this.SendPropertyChanging();
					this._ca_Id = value;
					this.SendPropertyChanged("ca_Id");
					this.Onca_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ca_Descripcion", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string ca_Descripcion
		{
			get
			{
				return this._ca_Descripcion;
			}
			set
			{
				if ((this._ca_Descripcion != value))
				{
					this.Onca_DescripcionChanging(value);
					this.SendPropertyChanging();
					this._ca_Descripcion = value;
					this.SendPropertyChanged("ca_Descripcion");
					this.Onca_DescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TbCargo_TbEmpleados", Storage="_TbEmpleados", ThisKey="ca_Id", OtherKey="em_cargo")]
		public EntitySet<TbEmpleados> TbEmpleados
		{
			get
			{
				return this._TbEmpleados;
			}
			set
			{
				this._TbEmpleados.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TbEmpleados(TbEmpleados entity)
		{
			this.SendPropertyChanging();
			entity.TbCargo = this;
		}
		
		private void detach_TbEmpleados(TbEmpleados entity)
		{
			this.SendPropertyChanging();
			entity.TbCargo = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TbEmpleados")]
	public partial class TbEmpleados : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _em_identificacion;
		
		private System.DateTime _em_fechaNacimiento;
		
		private string _em_nombre;
		
		private string _em_contrasena;
		
		private int _em_tipoId;
		
		private string _em_direccion;
		
		private int _em_cargo;
		
		private string _em_contacto;
		
		private EntityRef<TbCargo> _TbCargo;
		
		private EntityRef<TbTipoId> _TbTipoId;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onem_identificacionChanging(string value);
    partial void Onem_identificacionChanged();
    partial void Onem_fechaNacimientoChanging(System.DateTime value);
    partial void Onem_fechaNacimientoChanged();
    partial void Onem_nombreChanging(string value);
    partial void Onem_nombreChanged();
    partial void Onem_contrasenaChanging(string value);
    partial void Onem_contrasenaChanged();
    partial void Onem_tipoIdChanging(int value);
    partial void Onem_tipoIdChanged();
    partial void Onem_direccionChanging(string value);
    partial void Onem_direccionChanged();
    partial void Onem_cargoChanging(int value);
    partial void Onem_cargoChanged();
    partial void Onem_contactoChanging(string value);
    partial void Onem_contactoChanged();
    #endregion
		
		public TbEmpleados()
		{
			this._TbCargo = default(EntityRef<TbCargo>);
			this._TbTipoId = default(EntityRef<TbTipoId>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_em_identificacion", DbType="VarChar(30) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string em_identificacion
		{
			get
			{
				return this._em_identificacion;
			}
			set
			{
				if ((this._em_identificacion != value))
				{
					this.Onem_identificacionChanging(value);
					this.SendPropertyChanging();
					this._em_identificacion = value;
					this.SendPropertyChanged("em_identificacion");
					this.Onem_identificacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_em_fechaNacimiento", DbType="Date NOT NULL")]
		public System.DateTime em_fechaNacimiento
		{
			get
			{
				return this._em_fechaNacimiento;
			}
			set
			{
				if ((this._em_fechaNacimiento != value))
				{
					this.Onem_fechaNacimientoChanging(value);
					this.SendPropertyChanging();
					this._em_fechaNacimiento = value;
					this.SendPropertyChanged("em_fechaNacimiento");
					this.Onem_fechaNacimientoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_em_nombre", DbType="VarChar(70) NOT NULL", CanBeNull=false)]
		public string em_nombre
		{
			get
			{
				return this._em_nombre;
			}
			set
			{
				if ((this._em_nombre != value))
				{
					this.Onem_nombreChanging(value);
					this.SendPropertyChanging();
					this._em_nombre = value;
					this.SendPropertyChanged("em_nombre");
					this.Onem_nombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_em_contrasena", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string em_contrasena
		{
			get
			{
				return this._em_contrasena;
			}
			set
			{
				if ((this._em_contrasena != value))
				{
					this.Onem_contrasenaChanging(value);
					this.SendPropertyChanging();
					this._em_contrasena = value;
					this.SendPropertyChanged("em_contrasena");
					this.Onem_contrasenaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_em_tipoId", DbType="Int NOT NULL")]
		public int em_tipoId
		{
			get
			{
				return this._em_tipoId;
			}
			set
			{
				if ((this._em_tipoId != value))
				{
					if (this._TbTipoId.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onem_tipoIdChanging(value);
					this.SendPropertyChanging();
					this._em_tipoId = value;
					this.SendPropertyChanged("em_tipoId");
					this.Onem_tipoIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_em_direccion", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string em_direccion
		{
			get
			{
				return this._em_direccion;
			}
			set
			{
				if ((this._em_direccion != value))
				{
					this.Onem_direccionChanging(value);
					this.SendPropertyChanging();
					this._em_direccion = value;
					this.SendPropertyChanged("em_direccion");
					this.Onem_direccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_em_cargo", DbType="Int NOT NULL")]
		public int em_cargo
		{
			get
			{
				return this._em_cargo;
			}
			set
			{
				if ((this._em_cargo != value))
				{
					if (this._TbCargo.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onem_cargoChanging(value);
					this.SendPropertyChanging();
					this._em_cargo = value;
					this.SendPropertyChanged("em_cargo");
					this.Onem_cargoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_em_contacto", DbType="VarChar(60) NOT NULL", CanBeNull=false)]
		public string em_contacto
		{
			get
			{
				return this._em_contacto;
			}
			set
			{
				if ((this._em_contacto != value))
				{
					this.Onem_contactoChanging(value);
					this.SendPropertyChanging();
					this._em_contacto = value;
					this.SendPropertyChanged("em_contacto");
					this.Onem_contactoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TbCargo_TbEmpleados", Storage="_TbCargo", ThisKey="em_cargo", OtherKey="ca_Id", IsForeignKey=true)]
		public TbCargo TbCargo
		{
			get
			{
				return this._TbCargo.Entity;
			}
			set
			{
				TbCargo previousValue = this._TbCargo.Entity;
				if (((previousValue != value) 
							|| (this._TbCargo.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TbCargo.Entity = null;
						previousValue.TbEmpleados.Remove(this);
					}
					this._TbCargo.Entity = value;
					if ((value != null))
					{
						value.TbEmpleados.Add(this);
						this._em_cargo = value.ca_Id;
					}
					else
					{
						this._em_cargo = default(int);
					}
					this.SendPropertyChanged("TbCargo");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TbTipoId_TbEmpleados", Storage="_TbTipoId", ThisKey="em_tipoId", OtherKey="tid_Id", IsForeignKey=true)]
		public TbTipoId TbTipoId
		{
			get
			{
				return this._TbTipoId.Entity;
			}
			set
			{
				TbTipoId previousValue = this._TbTipoId.Entity;
				if (((previousValue != value) 
							|| (this._TbTipoId.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TbTipoId.Entity = null;
						previousValue.TbEmpleados.Remove(this);
					}
					this._TbTipoId.Entity = value;
					if ((value != null))
					{
						value.TbEmpleados.Add(this);
						this._em_tipoId = value.tid_Id;
					}
					else
					{
						this._em_tipoId = default(int);
					}
					this.SendPropertyChanged("TbTipoId");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TbTipoId")]
	public partial class TbTipoId : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _tid_Id;
		
		private string _tid_Nombre;
		
		private string _tid_Descripcion;
		
		private EntitySet<TbEmpleados> _TbEmpleados;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ontid_IdChanging(int value);
    partial void Ontid_IdChanged();
    partial void Ontid_NombreChanging(string value);
    partial void Ontid_NombreChanged();
    partial void Ontid_DescripcionChanging(string value);
    partial void Ontid_DescripcionChanged();
    #endregion
		
		public TbTipoId()
		{
			this._TbEmpleados = new EntitySet<TbEmpleados>(new Action<TbEmpleados>(this.attach_TbEmpleados), new Action<TbEmpleados>(this.detach_TbEmpleados));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tid_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int tid_Id
		{
			get
			{
				return this._tid_Id;
			}
			set
			{
				if ((this._tid_Id != value))
				{
					this.Ontid_IdChanging(value);
					this.SendPropertyChanging();
					this._tid_Id = value;
					this.SendPropertyChanged("tid_Id");
					this.Ontid_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tid_Nombre", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string tid_Nombre
		{
			get
			{
				return this._tid_Nombre;
			}
			set
			{
				if ((this._tid_Nombre != value))
				{
					this.Ontid_NombreChanging(value);
					this.SendPropertyChanging();
					this._tid_Nombre = value;
					this.SendPropertyChanged("tid_Nombre");
					this.Ontid_NombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tid_Descripcion", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string tid_Descripcion
		{
			get
			{
				return this._tid_Descripcion;
			}
			set
			{
				if ((this._tid_Descripcion != value))
				{
					this.Ontid_DescripcionChanging(value);
					this.SendPropertyChanging();
					this._tid_Descripcion = value;
					this.SendPropertyChanged("tid_Descripcion");
					this.Ontid_DescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TbTipoId_TbEmpleados", Storage="_TbEmpleados", ThisKey="tid_Id", OtherKey="em_tipoId")]
		public EntitySet<TbEmpleados> TbEmpleados
		{
			get
			{
				return this._TbEmpleados;
			}
			set
			{
				this._TbEmpleados.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TbEmpleados(TbEmpleados entity)
		{
			this.SendPropertyChanging();
			entity.TbTipoId = this;
		}
		
		private void detach_TbEmpleados(TbEmpleados entity)
		{
			this.SendPropertyChanging();
			entity.TbTipoId = null;
		}
	}
	
	public partial class verEmpleadosResult
	{
		
		private string _Identificacion;
		
		private System.DateTime _Fecha_Nacimiento;
		
		private string _Nombre;
		
		private string _Contrasena;
		
		private string _Tipo_Documento;
		
		private string _Direccion;
		
		private string _Cargo;
		
		private string _Telefono_de_Contacto;
		
		public verEmpleadosResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Identificacion", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string Identificacion
		{
			get
			{
				return this._Identificacion;
			}
			set
			{
				if ((this._Identificacion != value))
				{
					this._Identificacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Fecha Nacimiento]", Storage="_Fecha_Nacimiento", DbType="Date NOT NULL")]
		public System.DateTime Fecha_Nacimiento
		{
			get
			{
				return this._Fecha_Nacimiento;
			}
			set
			{
				if ((this._Fecha_Nacimiento != value))
				{
					this._Fecha_Nacimiento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(70) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contrasena", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Contrasena
		{
			get
			{
				return this._Contrasena;
			}
			set
			{
				if ((this._Contrasena != value))
				{
					this._Contrasena = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Tipo Documento]", Storage="_Tipo_Documento", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string Tipo_Documento
		{
			get
			{
				return this._Tipo_Documento;
			}
			set
			{
				if ((this._Tipo_Documento != value))
				{
					this._Tipo_Documento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direccion", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Direccion
		{
			get
			{
				return this._Direccion;
			}
			set
			{
				if ((this._Direccion != value))
				{
					this._Direccion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cargo", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string Cargo
		{
			get
			{
				return this._Cargo;
			}
			set
			{
				if ((this._Cargo != value))
				{
					this._Cargo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Telefono de Contacto]", Storage="_Telefono_de_Contacto", DbType="VarChar(60) NOT NULL", CanBeNull=false)]
		public string Telefono_de_Contacto
		{
			get
			{
				return this._Telefono_de_Contacto;
			}
			set
			{
				if ((this._Telefono_de_Contacto != value))
				{
					this._Telefono_de_Contacto = value;
				}
			}
		}
	}
	
	public partial class accederEmpleadoResult
	{
		
		private string _Identificacion;
		
		private System.DateTime _Fecha_Nacimiento;
		
		private string _Nombre;
		
		private string _Contrasena;
		
		private string _Tipo_Documento;
		
		private string _Direccion;
		
		private string _Cargo;
		
		private string _Telefono_de_Contacto;
		
		public accederEmpleadoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Identificacion", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string Identificacion
		{
			get
			{
				return this._Identificacion;
			}
			set
			{
				if ((this._Identificacion != value))
				{
					this._Identificacion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Fecha Nacimiento]", Storage="_Fecha_Nacimiento", DbType="Date NOT NULL")]
		public System.DateTime Fecha_Nacimiento
		{
			get
			{
				return this._Fecha_Nacimiento;
			}
			set
			{
				if ((this._Fecha_Nacimiento != value))
				{
					this._Fecha_Nacimiento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(70) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contrasena", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Contrasena
		{
			get
			{
				return this._Contrasena;
			}
			set
			{
				if ((this._Contrasena != value))
				{
					this._Contrasena = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Tipo Documento]", Storage="_Tipo_Documento", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string Tipo_Documento
		{
			get
			{
				return this._Tipo_Documento;
			}
			set
			{
				if ((this._Tipo_Documento != value))
				{
					this._Tipo_Documento = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direccion", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Direccion
		{
			get
			{
				return this._Direccion;
			}
			set
			{
				if ((this._Direccion != value))
				{
					this._Direccion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cargo", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
		public string Cargo
		{
			get
			{
				return this._Cargo;
			}
			set
			{
				if ((this._Cargo != value))
				{
					this._Cargo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Telefono de Contacto]", Storage="_Telefono_de_Contacto", DbType="VarChar(60) NOT NULL", CanBeNull=false)]
		public string Telefono_de_Contacto
		{
			get
			{
				return this._Telefono_de_Contacto;
			}
			set
			{
				if ((this._Telefono_de_Contacto != value))
				{
					this._Telefono_de_Contacto = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
